s = set()
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))
n = input("Enter the number you wanted: ")
s.add(int(n))

print(s)